steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/billreader-431408/streamlit-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/billreader-431408/streamlit-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
images:
- 'gcr.io/billreader-431408/streamlit-app'
options:
  logging: CLOUD_LOGGING_ONLY
