steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
images:
- 'gcr.io/$PROJECT_ID/streamlit-app'
